-- MySQL Script generated by MySQL Workbench
-- Sat Apr 16 14:30:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Escuela_Prueba
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Escuela_Prueba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Escuela_Prueba` DEFAULT CHARACTER SET utf8 ;
USE `Escuela_Prueba` ;

-- -----------------------------------------------------
-- Table `Escuela_Prueba`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela_Prueba`.`alumnos` (
  `idalumnos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `materia` VARCHAR(25) NOT NULL,
  `calificacion` DOUBLE NOT NULL,
  `estatus` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idalumnos`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
